### ISSUE TITLE
Max bounty hunter issues improvement

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#298]
An improvement idea is to check all of the open pull requests of the bounty hunter, and then check the state of the pull request review. 

If they have a pull request open but no review started, then it counts against their quota. 

If they have a pull request opened and also have a "review" in progress (perhaps there is an api to get a Boolean for this) then they are able to start working on another bounty. 

Next level beyond could be a 
one day "cool down". If there's longer than a 24 hour delay by the core team/reviewers, then "unlock" the bounty hunter to work on another issue. 

_Originally posted by @pavlovcik in https://github.com/ubiquity/bounty-bot/issues/245#issuecomment-1541195579_

**Comment by wannacfuture** [comment]
Let's clarify.

If a bounty hunter has opened pull request with no review, then the value of available_bounty_hunter_issue will decrease.(the initial value of available_bounty_hunter_issue will be max_bounty_hunter_issue config).

However, if the bounty hunter has opened pull request with no review, but the pull request is created more than 24 hours ago, then the value of available_bounty_hunter_issue will increase.

When the bounty hunter assigns themselves to an issue, the bot will calculate their available_bounty_hunter_issue value. If this value is zero, the bot will add a comment saying: "You cannot assign yourself to this issue because you have other open pull requests.".
