### ISSUE TITLE
Prevent Double Commenting

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#440]
In the `addComment` function (or whatever the name of the function is that we use everywhere in the code to add a comment) we should check the last comment in the conversation. If the last comment is from the bot, then the bot should edit that comment instead of posting another one. 

> Updated the wallet address for @pavlovcik successfully!	 Your new address: `0x4007CE2083c7F3E18097aeB3A39bb8eC149a341d`

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/ubiquibot/issues/410#issuecomment-1610792247_

**Comment by web4er** [comment]
I see double comment by the bot is not happening always. It happens when you edit your comment. 

Is removing the double comment in this case a good idea? Here is my analysis from my limited knowledge of the bot. 

A bot comment is usually just not a comment. It has side effects, e.g. saving wallet to DB. If you remove the double comment, you need to undo its side effects. 

If you change wallet, and then edit the comment to assign, both have side affects. I think double comment in this case should stay.  Here is an example https://github.com/web4er/ubi-iss-rep/issues/4#issuecomment-1612722021

Github already doesn't trigger the change if the comment was editing to same old comment. However, if you add space or something invisible to old comment, a double comment by the bot happens. In this case the double comment should be prevented. But instead of removing the double comment, a better approach is to improve the comment parser.  I see two approaches to improve the parser. 
1. Make it very strict e.g. if there are extra spaces, just ignore it.
2. Use regex and allow multiple white characters

**Comment by pavlovcik** [comment]
We can see the entire edit history and cross reference timestamps if necessary to track things down. Ultimately, when reviewing a conversation I think that the only information thats relevant is the final state of e.g. the registered wallet. 

Furthermore this proposal also solves for when a new contributor comments on a repository and the bot will reply with a help menu. If that new user edits their first comment, the bot will continue to post those tutorial comments again and again.

**Comment by pavlovcik** [comment]
Intuitively, the bot should adapt its response based on what it was responding to. 

In practice, this means that we should detect which comment was edited, and then edit the response of the bot in the immediately following comment.

**Comment by web4er** [comment]
I have started work on this. Based on what is available through GitHub API, this is my approach. 

Let's assume what the user is commenting are commands
- We already have information in the bot if it is `edited` comment or newly `created` comment by the user. 
- If it is an edited comment, we retrieve 2 comments since the `created_at` time of this edited comment.
- The first comment is the original initial comment by the user, and the second is the response by the bot. We do confirm the response by checking the username of the bot.
- We update the response comment by the bot. 
- We still use new comment from the bot as a fallback in case we can't find a response from the bot to an edited comment.  More about this below:

There are some valid reasons why we will not find a response from the bot.
- someone else comments on the issue before the user gets a response from the bot. 
- a user edits a normal comment to a command comment.
- bot was down and never responded to a command

There are some ways to handle the above cases, but it gets complicated and still leaves a chance of error.

It is a work in progress so anything can change. I am testing it for edge cases.

**Comment by web4er** [comment]
> Skipping `/assign` since no time labels are set to calculate the timeline

Oops, I will go ahead anyway. 

This was a tough one. The reason is, I couldn't find a way to retrieve the exact comment I wanted through Github API.  Github doesn't offer flexible serverside orderby and filters for comments. 

The solution we have is very much like I have described above. It is working well. However, I would like to describe a case, where there is clearly a bot response next to a command and the bot will not edit it but will go to fallback mode and add a new comment. We retrieve 30 comments since the `created_at` datetime of the edited comment. Unfortunately, Github uses this datetime to compare `updated_at` datetime of comments instead of `created_at`. In most cases, this works because the first comment we get is the edited comment, and next is the response the bot has to edit. But if users have edited about 30 comments or more above the target comment, these comments end up between the edited comment, and its response and we miss the response that we have to edit. 

The above case can be made less likely by increasing the comments we receive to more than 30, but I think in most cases, that would be unnecessary. Loading so many comments will just put a load on the bot. 

Here is the QA https://github.com/web4er/ubiquibot/issues/35

**Comment by pavlovcik** [comment]
@web4er I'm not sure how I forgot to set a price for this but your efforts are appreciated. I'll generate a reward for you in a bit.
