### ISSUE TITLE
Local development issue

### ISSUE THREAD

**Issue by whilefoo** [ubiquity/ubiquibot#569]
When I run the bot locally using webhook proxy, it only works for the first webhook received after that it doesn't respond anymore. For example when I start with `yarn start` and post a comment, the bot receives the webhook and processes it, but then I post another comment and the bot doesn't get the webhook. It's really frustrating during development because you have to start and stop the bot for every event.
The webhook proxy might the problem but needs more investigating.

**Comment by web4er** [comment]
I am facing the same issue.

**Comment by web4er** [comment]
I have fixed it and here are the details. The problem was in the wildcardProcessors where local development server was getting stuck in an infinite while loop. 

https://github.com/ubiquity/ubiquibot/blob/6ad07d30e489d52a079e88bdaf11790d8a88ecd7/src/handlers/wildcard/weekly/action.ts#L34

This part inside a while loop checks if the payload has an organization, but there is nothing to stop the while loop if payload doesn't have an organization. That is why, it was working in production, because it is an organization, and it is getting stuck for local devs as they are not an organization. 

Another problem I had to fix after fixing this one was, there was some code, which probably didn't run on the local for long time, because it was supposed to run after the loop, and the loop never ended, and that code wasn't tested much on the local. Each of the following functions was failing.

```
await htmlImage(summaryInfo);
await compositeImage();
await processTelegram(dataPadded);
```

The first two functions couldn't find the required images and `assets` directory in the build. I have fixed it by updating the build command in packages.json

` "build": "tsc && copyfiles src/assets/images/* lib/",`

The telegram function was ok but it was trying to send message even if telegram token is not set. I have updated it to just ignore sending message if token is not set. 

Initially, in the troubleshoot, I also looked into webhook proxy. It turned to be not a webhook proxy issue, but this is what I have found. Troubleshooting smee.io was slow & hard. I couldn't find request details. However, I looked for its alternatives and found webhookrelay.com much more awesome. It has free plan, speed of receiving events was excellent, you can see the requests, and responses in the web, and your local CLI. You can replay events. It was webhookrelay.com that provided me a confirmation that it is not a webhook proxy issue.
