### ISSUE TITLE
Edit Instead of Double Post

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#601]
> How about a hot fix so that the bot will never double post? Does that make sense? It checks the last comment in the conversation, and if it is the last comment, it will edit it instead of double posting. 

> It will band-aid a lot of the small edge cases like when it aggressively follows up a ton of times, or what we were discussing earlier in this conversation.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/issues/597#issuecomment-1673497830_

**Comment by ByteBallet** [comment]
Why can't I be assigned?

**Comment by pavlovcik** [comment]
@0xcodercrane @wannacfuture is the bot down?

**Comment by pavlovcik** [comment]
Oh wait we just renamed the command sorry. Try `/start` now!

**Comment by ByteBallet** [comment]
@pavlovcik
Could you please let me know if it is okay to use https://github.com/ubiquity/ubiquibot/blob/development/src/helpers/issue.ts#L157 ?
I am not sure about that because I found that function is used nowhere and instead https://github.com/ubiquity/ubiquibot/blob/development/src/helpers/issue.ts#L199 were used frequently.
Are they different?

**Comment by pavlovcik** [comment]
> if it is okay to use

@wannacfuture

**Comment by wannacfuture** [comment]
@ByteBallet  you should use getgetAllIssueComments function.

**Comment by ByteBallet** [comment]
Okay. Got it.

**Comment by pavlovcik** [comment]
@rndquu I remember you are not a supporter of this task citing a reason that this will make bot debugging more difficult.  

We can see the edit history of the comment and time stamp of each edit. Is that not sufficient to quell your concern? 

@web4er as I recall you simply stated that we should focus on fixing the root problem. 

My response was that this solution isn't mutually exclusive to solving the root problem, and will make the conversations a lot neater while we take our time to solve the root problem.

**Comment by rndquu** [comment]
Another point not in favour of editing comments is that some of our tools (ex: https://pay.ubq.fi/audit) and features (the bot's `/autopay` command which toggles automatic payout for the issue it is used in) rely on a full issue's comment history. So we don't want a permit URL comment to be edited (because the audit tool can not read the history of edited comments) or the `/autopay` command to be rewritten (because it simply breaks the feature).

**Comment by pavlovcik** [comment]
> Another point not in favour of editing comments is that some of our tools (ex: https://pay.ubq.fi/audit) and features (the bot's `/autopay` command which toggles automatic payout for the issue it is used in) rely on a full issue's comment history. So we don't want a permit URL comment to be edited (because the audit tool can not read the history of edited comments) or the `/autopay` command to be rewritten (because it simply breaks the feature).

This is a valid problem scenario. Unforeseen edge cases with the order of bot comments can break the functionality of our other tooling.

**Comment by Keyrxng** [comment]
Well thinking about just these points, it wouldn't be hard to check whether the bot's last comment contained any of the sensitive stuff we don't want changed and if it does then just post a new comment rather than replacing it?

Specifically those two points, ```"/autopay"``` and any comment with ```"content.body.includes("https://pay.ubq.fi?claim="``` should be skipped over. I haven't looked at the /audit stuff in depth much yet to weigh in there.

Happy to hold fire, happy to get stuck in finding a solution but easy either way.

**Comment by pavlovcik** [comment]
The audit app has similar logic. Basically it just parses GitHub comments from the bot, containing the pay.ubq.fi url.

**Comment by rndquu** [comment]
> Specifically those two points, "/autopay" and any comment with "content.body.includes("https://pay.ubq.fi?claim=" should be skipped over. 

We can't cover all of the edge cases, something will definitely be missed. Again this brings us to [unit testing](https://github.com/orgs/ubiquity/discussions/88#discussioncomment-6811536) because with a decent test coverage we could be sure (to some extent) that the "edit comments" feature doesn't break anything.

**Comment by rndquu** [comment]
Closing this one because editing bot's comments [breaks](https://github.com/ubiquity/ubiquibot/issues/601#issuecomment-1690784123) other bot's functionality
