### ISSUE TITLE
Reopened & Unassigned

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#681]
The bot should be careful to not unassign like this when a task is reopened. It should reset the "timer" e.g. to be a full 7 days again.

> @whilefoo please be sure to review this conversation and implement any necessary fixes. Unless this is closed as completed, its payment of **450.0 WXDAI** will be deducted from your next bounty.

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/ubiquibot/issues/500#issuecomment-1694619062_

**Comment by wannacfuture** [comment]
https://github.com/ubiquity/ubiquibot/issues/685#issuecomment-1698760710

The solution will be similar.

we will find bot's comment saying "please be sure to review this conversation ..."
and consider that comment's createdAt as the activity time of the hunter as well.

**Comment by Keyrxng** [comment]
happy to take this if someone can assign it to me as I'm waiting for prs and haven't much to do this weekend 🤷‍♂️

**Comment by Keyrxng** [comment]
I will catch this tomorrow

**Comment by Keyrxng** [comment]
woops missed the reminder on this one

**Comment by 0xcodercrane** [comment]
Why conversationRewards includes @Keyrxng he is an assigneed seems bug.

**Comment by Keyrxng** [comment]
Thanks @0xcodercrane

So conversation rewards are only for non-assignees, is that across issues, discussions and prs?

**Comment by Keyrxng** [comment]
- https://github.com/Keyrxng/UbiquityBotTesting/issues/30#issuecomment-1727659530

- https://github.com/Keyrxng/UbiquityBotTesting/issues/45#issuecomment-1727658931

I just ran a fresh dev branch build after seeing @whilefoo comment on tg about hitting errors with events. No errors with events, but seems like the bot is still unassigning after a closed issue is re-opened see [example](https://github.com/Keyrxng/UbiquityBotTesting/issues/40#issuecomment-1727678674) & [example](https://github.com/Keyrxng/UbiquityBotTesting/issues/19#issuecomment-1727694011) 

The first two linked comments show that the bot spammed the comment 4 times for allocated duration has ended, these issues were just open and not reopened. This happened across 6 issues that the duration had expired on. Been a few days since I've run the bot right enough so I rightfully should have been unassigned but the spamming? Is that a product of not having run the bot for days, you folks would have a better idea if it's happening on other issues as you'll see far more of these events live than I will.
