### ISSUE TITLE
/start no wallet error

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot#924]
I assume the bot failed to assign the contributor because they never set a wallet. This is urgent to throw this error for new would be contributors. 

Check if they don't have a wallet registered. Warn them with an instruction that they need to set their wallet first. Explain how to set it in the warning. 

Looks like new members are unable to register, including @EresDev 

This is a showstopper as payment permits can not be generated without a registered wallet address. 

Diagnose and fix the root issue. Will set a time estimate after a diagnosis is provided here.

### Examples

https://github.com/ubiquity/devpool-directory-bounties/issues/24#issuecomment-2021521363

> /start

_Originally posted by @okhot in https://github.com/ubiquity/devpool-directory-bounties/issues/20#issuecomment-2018292322_

**Comment by Keyrxng** [comment]
@pavlovcik @rndquu 

Is the bot running in prod right now running from `ubiquibot/development`? That's where I'm checked-out from

I don't believe it was because the contributor hadn't yet set a wallet up because the dialogue below would render regardless of wallet address

![image](https://github.com/ubiquity/ubiquibot/assets/106303466/99adabf8-c0d9-4eee-a7ae-df632f89457a)

**Comment by 0x4007** [comment]
That's a good observation. 

It would be best if you can test for this somehow with a new profile though. 

The only other hypothesis I have is something to do with the profile parser. In the past like a long time ago, I remember when a brand new (empty) GitHub profile would try and start, the bot would crash expecting some different type of schema for the profile. 

Perhaps that is related, maybe you can make the profile parser more lenient or something. It probably is caused by the JSON validator. 

I removed the time estimate to allow you the chance to diagnose first

**Comment by Keyrxng** [comment]
I'll see if I can try reproduce. I appreciate the help and time

**Comment by rndquu** [comment]
> Is the bot running in prod right now running from `ubiquibot/development`?

As far as I remember the prod is running on either https://github.com/pavlovcik/ubiquibot/tree/refactor/move-to-delegated-compute either https://github.com/ubiquity/ubiquibot/tree/refactor/move-to-delegated-compute

@gentlementlegen might know better

**Comment by gentlementlegen** [comment]
Last time I checked it was https://github.com/pavlovcik/ubiquibot/tree/refactor/move-to-delegated-compute and I still do believe it is the case.

**Comment by 0x4007** [comment]
Just checked Netlify. It says https://github.com/pavlovcik/ubiquibot/commits/refactor/move-to-delegated-compute/ `@head`

**Comment by EresDev** [comment]
> I'll see if I can try reproduce. I appreciate the help and time

I think I have a lead on this issue but I can't confirm because the branch **move-to-delegated-compute** on the deploy doesn't have updated schemas. That is why I don't have a fully working local instance. I will need time to get there. But if anyone else has it then here is a tip. 

The problem appears to be with `int4` datatype used in database. Especially in `locations.issue_id` column. But it can be with other int4 types columns too, but it is a good start. 

For my example case `issue_id`: 2210087643
  
you see issue id above, and the range for `int4` is -2147483648 to +2147483647 and issue_id above is out of range. 

Try this fix: 

change the datatype of locations.issue_id to int8

You may get some more out of range ids and probably will have to change all or most `int4` to `int8`. 

And why a clear error wasn't given by the bot that is another problem to solve if we want to continue using the the bot. 

Plus, some more ids of github like `comment_id` are catching up too, in my example case, comment_id: 2022299611

**Comment by gentlementlegen** [comment]
@EresDev If you need to use locally the latest schema of the DB I had made a dump of it in one PR that is not merged here https://github.com/ubiquity/ubiquibot/pull/923https://github.com/ubiquity/ubiquibot/pull/923 
This one is the latest schema of the current database. After your comment I can update these columns as well.

**Comment by EresDev** [comment]
> After your comment I can update these columns as well.

yes please go ahead and update these columns.

**Comment by gentlementlegen** [comment]
@EresDev I changed all these int4 to int8, so the table looks like this
```
create table "public"."locations" (
    "id" integer not null default nextval('location_id_seq1'::regclass),
    "node_id" character varying(255),
    "node_type" character varying(255),
    "updated" timestamp with time zone,
    "created" timestamp with time zone not null default now(),
    "node_url" text,
    "user_id" bigint,
    "repository_id" bigint,
    "organization_id" bigint,
    "comment_id" bigint,
    "issue_id" bigint
);
```

I do no know if that fixes the issue but it is live now, if you can please try it out.
After your wallet query the error is very vague and doesn't give any info
```
{
  "error": {},
  "caller": "renderCatchAll",
  "revision": null,
  "handlerType": {
    "type": "main",
    "actions": [
      null
    ]
  },
  "activeHandler": "commentCreated"
}
```

**Comment by 0x4007** [comment]
@EresDev moment of truth, why don't you try?

**Comment by EresDev** [comment]
> After your wallet query the error is very vague and doesn't give any info

I got a clear error message with my local instance somehow. Why many of the supabase logs are like this is also an issue.  I have doubt that this just fixes `wallet` command and not `/start`. I am going to test it in some other issue and will report here.

These IDs should also be updated in other tables if we want to continue using the ubiquibot v1. But it is okay to ignore if  v2 is coming soon.

**Comment by EresDev** [comment]
> I have doubt that this just fixes wallet command and not /start. 

`/start` command is also working fine. I have tested it on [an old issue](https://github.com/ubiquibot/production/issues/40#issuecomment-2026947778) and [a recent issue](https://github.com/ubiquity/cloudflare-deploy-action/issues/8#issuecomment-2027011185).

**Comment by 0x4007** [comment]
Alright well this was sort of a weird task to price but one idea is to split the reward

**Comment by 0x4007** [comment]
I feel that it's really a coin toss to get claims to work on mobile. Anybody else having issues? We should really consider an end to end test with cypress etc because this is getting a bit annoying. 

![image](https://github.com/ubiquity/ubiquibot/assets/4975670/11528286-dfde-44b0-abaf-5f949f0be570)

**Comment by jordan-ae** [comment]
@pavlovcik this happened to me a couple of times yesterday. I thought a service was down or something so I stopped trying. 
But e2e Cypress test would most definitely help catch such.
