### ISSUE TITLE
Debug Admin Only Permit Generation

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubiquibot#927]
> I wonder if it's worth debugging why only admins can generate permits on v1 bot. 

_Originally posted by @0x4007 in https://github.com/ubiquity/work.ubq.fi/issues/41#issuecomment-2108901126_

**Comment by gentlementlegen** [comment]
The associated log error that usually comes with this is
```json
{
  "error": {
    "name": "HttpError",
    "status": 404,
    "request": {
      "url": "https://api.github.com/orgs/ubiquity/memberships/ubiquity",
      "method": "GET",
      "headers": {
        "accept": "application/vnd.github.v3+json",
        "user-agent": "probot/12.3.3 octokit-core.js/3.6.0 Node.js/20.12.0 (linux; x64)",
        "authorization": "token [REDACTED]"
      },
      "request": {
        "retryCount": 1
      }
    },
    "response": {
      "url": "https://api.github.com/orgs/ubiquity/memberships/ubiquity",
      "data": {
        "message": "Not Found",
        "documentation_url": "https://docs.github.com/rest/orgs/members#get-organization-membership-for-a-user"
      },
      "status": 404,
      "headers": {
        "date": "Mon, 13 May 2024 19:24:52 GMT",
        "vary": "Accept-Encoding, Accept, X-Requested-With",
        "server": "GitHub.com",
        "content-type": "application/json; charset=utf-8",
        "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
        "x-frame-options": "deny",
        "content-encoding": "gzip",
        "x-ratelimit-used": "21",
        "x-xss-protection": "0",
        "transfer-encoding": "chunked",
        "x-ratelimit-limit": "7150",
        "x-ratelimit-reset": "1715631888",
        "x-github-media-type": "github.v3; format=json",
        "x-github-request-id": "BA3C:26DB23:3839439:603C045:66426904",
        "x-ratelimit-resource": "core",
        "x-ratelimit-remaining": "7129",
        "x-content-type-options": "nosniff",
        "content-security-policy": "default-src 'none'",
        "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
        "access-control-allow-origin": "*",
        "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
        "x-accepted-github-permissions": "members=read",
        "x-github-api-version-selected": "2022-11-28"
      }
    }
  },
  "caller": "renderCatchAll",
  "revision": null,
  "handlerType": {
    "type": "main",
    "actions": [
      null
    ]
  },
  "activeHandler": "issueClosed"
}
```
[Related Supabase entry](https://supabase.com/dashboard/project/wfzpewmlyiozupulbuur/editor/28943?sort=created%3Adesc&filter=level%3Aneq%3Ainfo&filter=id%3Aeq%3A897042)
I suspect some call to Octokit to check if the user belongs the the organization failing that is not caught and leads to the error.

**Comment by molecula451** [comment]
![image_2024-05-14_051857954](https://github.com/ubiquity/ubiquibot/assets/41552663/9eb8bea5-c5ea-494e-b1da-7d5f41bd12d0)

I'm aware the i can generate permits on repos where I see the  "settings" at  the end of the repo:

as you may see:

https://github.com/ubiquibot/assistive-pricing/issues/2

as  oppose to:

![Screenshot from 2024-05-14 05-21-17](https://github.com/ubiquity/ubiquibot/assets/41552663/1cf76210-0e8a-4635-8a25-fd35b4508fd2)

**Comment by gentlementlegen** [comment]
@molecula451 Yep that's one of the criteria, but also being a `billing manager` in the organization should allow for generating permits despite not having rights on the specific repo.

**Comment by molecula451** [comment]
> @molecula451 Yep that's one of the criteria, but also being a `billing manager` in the organization should allow for generating permits despite not having rights on the specific repo.

I agree, it's more like we're missing something on the bot level

**Comment by gentlementlegen** [comment]
I have spent quite some time checking this today, and couldn't pinpoint the issue.

First, I assume that the latest deployment of the bot is inside the [refactor/move-to-delegate-compute](https://github.com/ubiquity/ubiquibot/tree/refactor/move-to-delegated-compute) branch. 

According to the error, it happened on `issueClosed` and poking the API at https://api.github.com/orgs/ubiquity/memberships/ubiquity which returned a 404 triggering the error.

First it is weird to have a 404 since I should be in the members so far. Second, the only spot where this is called would be in [checkUserPermissionForOrg](https://github.com/ubiquity/ubiquibot/blob/abf320c23cc216d9984559a8d008902b492370c5/src/handlers/comment/handlers/issue-closed.ts#L119). As you can see, it is wrapped in a try catch clause.

Locally, I get error logs but no crash. Inside of Supabase, the record indicates that the associated message is [action has an uncaught error](https://github.com/ubiquity/ubiquibot/blob/626cae8fcf5b60ec1ccb49df8dd2f250df046ff9/src/bindings/event.ts#L239) which would mean the error got bubbled all the way up. My theory is that this error is not the real one, and the stack is actually destroyed somewhere. Sadly I do not have access to Cloudflare to debug there.

---

Edit: could finally repro the error. It seems the catch doesn't catch, going through the rabbit hole.

**Comment by 0x4007** [comment]
> My theory is that this error is not the real one, and the stack is actually destroyed somewhere.

Sorry for being late to comment on this. It's a valid theory because i manually implemented a ton of display logic for managing the stack to seamlessly support GitHub comments, Supabase logs, console logs. 

There's a good possibility that there is a mistake somewhere. I also was trimming some of the stack to not log the internals of the logging function, for example.

**Comment by gentlementlegen** [comment]
No worries, in this case it was the check for collaborator status that was not wrapped within a try catch thus would bubble up the error all the way up hence the strange error. Should hopefully be fixed by https://github.com/ubiquity/ubiquibot/pull/928
